# Warp Launch Configuration
#
#
# Use this to start a certain configuration of windows, tabs, and panes.
# Open the launch configuration palette to access and open any launch configuration.
#
# This file defines your launch configuration.
# More on how to do so here:
# https://docs.warp.dev/features/session-management/launch-configurations
#
# All launch configurations are stored under ~/.warp/launch_configurations.
# Edit them anytime!
#
# You can also add commands that run on-start for your launch configurations like so:
# ---
# name: Example with Command
# windows:
#  - tabs:
#      - layout:
#          cwd: /Users/warp-user/project
#          commands:
#            - exec: code .

---
name: Launch Config
windows:
    - tabs:
          - title: home
            layout:
                cwd: /Users/damiantziamtzis
          - title: klave docs
            layout:
                cwd: /Users/damiantziamtzis/Developer/work/docs
            color: yellow
          - title: klave
            layout:
                split_direction: horizontal
                panes:
                    - cwd: /Users/damiantziamtzis/Developer/work/platform
                    - cwd: /Users/damiantziamtzis/Developer/work/platform
            color: green
          - title: softmetal
            layout:
                cwd: /Users/damiantziamtzis/Developer/work/softmetal
            color: blue
          - title: websites
            layout:
                cwd: /Users/damiantziamtzis/Developer/work/websites
            color: red
